stages:
  - checkstyle_backend

checkstyle_backend:
  stage: checkstyle_backend
  image: gradle:8.5-jdk21
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never 
  before_script:
    - cd BackEnd  
  script:
    - gradle checkstyleMain checkstyleTest --no-daemon
  after_script:
    - chmod +x scripts/ci/generate-codequality-report-from-checkstyle.sh
    - scripts/ci/generate-codequality-report-from-checkstyle.sh build/reports/checkstyle/main.xml > checkstyle-report.json
  artifacts:
    when: always
    paths:
      - BackEnd/build/reports/checkstyle/
    reports:
      codequality:
        - BackEnd/checkstyle-report.json
  allow_failure: false
