stages:
  - checkstyle
  - build
  - test

checkstyle_backend:
  stage: checkstyle
  image: gradle:8.13-jdk21
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  before_script:
    - cd BackEnd
  script:
    - gradle checkstyleMain checkstyleTest --no-daemon
  after_script:
    - chmod +x scripts/ci/generate-codequality-report-from-checkstyle.sh
    - scripts/ci/generate-codequality-report-from-checkstyle.sh build/reports/checkstyle/main.xml > checkstyle-report.json
  artifacts:
    when: always
    paths:
      - BackEnd/build/reports/checkstyle/
    reports:
      codequality:
        - BackEnd/checkstyle-report.json
  allow_failure: false

checkstyle_frontend:
  stage: checkstyle
  image: node:22
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  before_script:
    - cd FrontEnd
    - npm ci
  script:
    - npx prettier --check "src/**/*.{js,ts,jsx,tsx,json,css,scss,md}"
    - npx eslint "src/**/*.{js,ts,jsx,tsx}" --max-warnings=0
  allow_failure: false

build_backend:
  stage: build
  image: gradle:8.13-jdk21
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  script:
    - cd BackEnd
    - gradle build --no-daemon
  artifacts:
    paths:
      - BackEnd/build/libs/

build_frontend:
  stage: build
  image: node:22
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  script:
    - cd FrontEnd
    - npm install
    - npm run build
  artifacts:
    paths:
      - FrontEnd/build/

test_backend:
  stage: test
  image: gradle:8.13-jdk21
  tags:
    - gitlab-runner
  needs:
    - job: build_backend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  script:
    - cd BackEnd
    - gradle test --no-daemon
  artifacts:
    paths:
      - BackEnd/build/reports/tests/
