stages:
  - checkstyle_backend
  - checkstyle_frontend

checkstyle_backend:
  stage: checkstyle_backend
  image: gradle:8.5-jdk21
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  before_script:
    - cd BackEnd
  script:
    - gradle checkstyleMain checkstyleTest --no-daemon
  after_script:
    - chmod +x scripts/ci/generate-codequality-report-from-checkstyle.sh
    - scripts/ci/generate-codequality-report-from-checkstyle.sh build/reports/checkstyle/main.xml > checkstyle-report.json
  artifacts:
    when: always
    paths:
      - BackEnd/build/reports/checkstyle/
    reports:
      codequality:
        - BackEnd/checkstyle-report.json
  allow_failure: false

checkstyle_frontend:
  stage: checkstyle_frontend
  image: node:18
  tags:
    - gitlab-runner
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never
  before_script:
    - cd FrontEnd
    - npm ci
  script:
    - npx prettier --check "src/**/*.{js,ts,jsx,tsx,json,css,scss,md}"
    - npx eslint "src/**/*.{js,ts,jsx,tsx}" --max-warnings=0
  allow_failure: false
