spring:
  config:
    import: optional:file:.env[.properties]
  # PostgreSQL DataSource 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      maximumPoolSize: 50
      minimumIdle: 5
      idle-timeout: 60000
      max-lifetime: 900000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 20000

  #  data:
  #    # Redis 설정
  #    redis:
  #      host: ${SPRING_DATA_REDIS_HOST}
  #      port: ${SPRING_DATA_REDIS_PORT}
  #      ssl:
  #        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED}
  #
  # GOOGLE 소셜 로그인 환경변수
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email
        provider:
          google:
            authorization-uri: ${GOOGLE_AUTHORIZATION_URI}
            token-uri: ${GOOGLE_TOKEN_URI}
            user-info-uri: ${GOOGLE_USER_INFO_URI}
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}

    jwt:
      secret-key: ${JWT_SECRET}
      expiration-time: ${JWT_EXPIRATION}
      issuer: whiskeep

decorator:
  datasource:
    p6spy:
      enable-logging: ${DECORATOR_DATASOURCE_P6SPY_ENABLE_LOGGING}

ocr:
  api-url: ${FAST_API_URL}

##AWS
#cloud:
#  aws:
#    credentials:
#      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
#      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
#    region:
#      static: ${CLOUD_AWS_REGION_STATIC}   # 버킷의 리전
#    s3:
#      bucket: ${CLOUD_AWS_S3_BUCKET}   # 버킷 이름
#    stack:
#      auto: ${CLOUD_AWS_STACK_AUTO}
#
## OPENAI 환경변수
#openai:
#  uri: https://api.openai.com/v1/chat/completions
#  model: ${OPENAI_MODEL}
#  secret-key: ${OPENAI_SECRET_KEY}
